#version 450 core

const int GROUP_SIZE = 64;

layout(local_size_x = 1, local_size_y = 64) in;
layout(r11f_g11f_b10f, binding = 0) uniform restrict readonly image2D u_input_image;
layout(r11f_g11f_b10f, binding = 1) uniform restrict writeonly image2D u_output_image;

const int M = 13;
const int N = 2 * M + 1;

// sigma = 3 support 0.9999
const float coeffs[N] = float[N](
0.0000,	0.0000,	0.0002,	0.0005,	0.0015,	0.0039,	0.0089,	0.0182,	0.0334,	0.0549,	0.0807,	0.1062,	0.1253,	
0.1324,	0.1253,	0.1062,	0.0807,	0.0549,	0.0334,	0.0182,	0.0089,	0.0039,	0.0015,	0.0005,	0.0002,	0.0000,	0.0000
);

const int CACHE_SIZE = GROUP_SIZE + 2 * M;

const int LOAD = (CACHE_SIZE + (GROUP_SIZE - 1)) / GROUP_SIZE;

shared vec4 cache[CACHE_SIZE];

void main()
{
	ivec2 size = imageSize(u_input_image);
	ivec2 pixel_coord = ivec2(gl_GlobalInvocationID.xy);

	int origin = int(gl_WorkGroupID.y) * GROUP_SIZE - M;

	for (int i = 0; i < LOAD; ++i)
	{
		int local = int(gl_LocalInvocationID.y) * LOAD + i;
		if (local < CACHE_SIZE)
		{
			int pc = origin + local;

			if (pc >= 0 && pc < size.y)
				cache[local] = imageLoad(u_input_image, ivec2(pixel_coord.x, pc));
		}
	}

	memoryBarrierShared();
	barrier();

	if (pixel_coord.x < size.x && pixel_coord.y < size.y)
	{
		vec4 sum = vec4(0.0);

		for (int i = 0; i < N; ++i)
		{
			ivec2 pc = pixel_coord + ivec2(0, i - M);
			if (pc.y < 0) pc.y = 0;
			if (pc.y >= size.y) pc.y = size.y - 1;

			int local = pc.y - origin;

			sum += coeffs[i] * cache[local];
		}

		imageStore(u_output_image, pixel_coord, sum);
	}
}